# Generated by Django 5.0.7 on 2024-08-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0003_alter_pickuprequest_pickup_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuprequest',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
